repos:
- repo: https://github.com/asottile/seed-isort-config
  rev: "v1.2.0"
  hooks:
  - id: seed-isort-config
    entry: seed-isort-config
    args: [--application-directories=./server/]
    files: requirements.txt
    language: python
    language_version: python3.9
    always_run: false
- repo: https://github.com/pre-commit/mirrors-isort
  rev: "v4.3.21"
  hooks:
  - id: isort
    entry: isort
- repo: https://github.com/ambv/black
  rev: "20.8b1"
  hooks:
    - id: black
      name: black
      entry: black -l 120
      language: python
      language_version: python3.9
      types: [python]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v1.4.0"
  hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      language_version: python3.9
      types: [python]
      exclude: _pb2.py$
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: "v1.19.1"
  hooks:
    - id: prettier
      name: prettier
      entry: prettier --config ./client/.prettierrc.js --write
      language: node
      files: \.(js|ts|less|html)$
      exclude: ^server/
- repo: https://github.com/pre-commit/mirrors-eslint
  sha: master
  hooks:
    - id: eslint
      name: eslint
      entry: eslint
      language: node
      files: \.(js)$
      additional_dependencies: ["eslint", "eslint-plugin-jasmine"]
- repo: git://github.com/awebdeveloper/pre-commit-tslint/
  sha: master
  hooks:
    - id: tslint
      name: tslint
      entry: tslint
      language: node
      files: \.(ts)$
      additional_dependencies: ["tslint", "typescript"]
